// <auto-generated />
namespace PS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class custclassadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(custclassadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202009011215300_cust class added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
