// <auto-generated />
namespace PS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNullabletocars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNullabletocars));
        
        string IMigrationMetadata.Id
        {
            get { return "202009161708531_Add Nullable to cars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
